import Foundation

struct CountryData {
    static let allCountries: [Country] = [
        // ─── AFRICA ───
        Country(name: "Algeria", flag: "🇩🇿", code: "DZ", continent: .africa, capital: "Algiers", funFact: "Largest country in Africa"),
        Country(name: "Angola", flag: "🇦🇴", code: "AO", continent: .africa, capital: "Luanda", funFact: "Has a machete on its flag"),
        Country(name: "Benin", flag: "🇧🇯", code: "BJ", continent: .africa, capital: "Porto-Novo", funFact: "Birthplace of the Vodun religion"),
        Country(name: "Botswana", flag: "🇧🇼", code: "BW", continent: .africa, capital: "Gaborone", funFact: "Home to the Okavango Delta"),
        Country(name: "Burkina Faso", flag: "🇧🇫", code: "BF", continent: .africa, capital: "Ouagadougou", funFact: "Name means 'Land of honest people'"),
        Country(name: "Burundi", flag: "🇧🇮", code: "BI", continent: .africa, capital: "Gitega", funFact: "One of the smallest countries in Africa"),
        Country(name: "Cabo Verde", flag: "🇨🇻", code: "CV", continent: .africa, capital: "Praia", funFact: "An island country with 10 islands"),
        Country(name: "Cameroon", flag: "🇨🇲", code: "CM", continent: .africa, capital: "Yaoundé", funFact: "Known as 'Africa in miniature'"),
        Country(name: "Central African Republic", flag: "🇨🇫", code: "CF", continent: .africa, capital: "Bangui", funFact: "Home to western lowland gorillas"),
        Country(name: "Chad", flag: "🇹🇩", code: "TD", continent: .africa, capital: "N'Djamena", funFact: "Flag looks almost identical to Romania's"),
        Country(name: "Comoros", flag: "🇰🇲", code: "KM", continent: .africa, capital: "Moroni", funFact: "Known as the 'Perfume Islands'"),
        Country(name: "Congo", flag: "🇨🇬", code: "CG", continent: .africa, capital: "Brazzaville", funFact: "Shares the Congo River with DR Congo"),
        Country(name: "DR Congo", flag: "🇨🇩", code: "CD", continent: .africa, capital: "Kinshasa", funFact: "Has the second-largest rainforest"),
        Country(name: "Côte d'Ivoire", flag: "🇨🇮", code: "CI", continent: .africa, capital: "Yamoussoukro", funFact: "Has the world's largest church"),
        Country(name: "Djibouti", flag: "🇩🇯", code: "DJ", continent: .africa, capital: "Djibouti", funFact: "One of the hottest countries on Earth"),
        Country(name: "Egypt", flag: "🇪🇬", code: "EG", continent: .africa, capital: "Cairo", funFact: "Home to the Great Pyramids of Giza"),
        Country(name: "Equatorial Guinea", flag: "🇬🇶", code: "GQ", continent: .africa, capital: "Malabo", funFact: "Only African country with Spanish as official language"),
        Country(name: "Eritrea", flag: "🇪🇷", code: "ER", continent: .africa, capital: "Asmara", funFact: "Has an olive branch on its flag"),
        Country(name: "Eswatini", flag: "🇸🇿", code: "SZ", continent: .africa, capital: "Mbabane", funFact: "One of the last absolute monarchies"),
        Country(name: "Ethiopia", flag: "🇪🇹", code: "ET", continent: .africa, capital: "Addis Ababa", funFact: "Has its own unique calendar"),
        Country(name: "Gabon", flag: "🇬🇦", code: "GA", continent: .africa, capital: "Libreville", funFact: "Over 80% covered in rainforest"),
        Country(name: "Gambia", flag: "🇬🇲", code: "GM", continent: .africa, capital: "Banjul", funFact: "Smallest country in mainland Africa"),
        Country(name: "Ghana", flag: "🇬🇭", code: "GH", continent: .africa, capital: "Accra", funFact: "Named after an ancient West African empire"),
        Country(name: "Guinea", flag: "🇬🇳", code: "GN", continent: .africa, capital: "Conakry", funFact: "Has the same colors as Mali's flag reversed"),
        Country(name: "Guinea-Bissau", flag: "🇬🇼", code: "GW", continent: .africa, capital: "Bissau", funFact: "Has a black star on its flag"),
        Country(name: "Kenya", flag: "🇰🇪", code: "KE", continent: .africa, capital: "Nairobi", funFact: "Has a Maasai shield on its flag"),
        Country(name: "Lesotho", flag: "🇱🇸", code: "LS", continent: .africa, capital: "Maseru", funFact: "Entirely surrounded by South Africa"),
        Country(name: "Liberia", flag: "🇱🇷", code: "LR", continent: .africa, capital: "Monrovia", funFact: "Flag resembles the US flag"),
        Country(name: "Libya", flag: "🇱🇾", code: "LY", continent: .africa, capital: "Tripoli", funFact: "Has a crescent and star on its flag"),
        Country(name: "Madagascar", flag: "🇲🇬", code: "MG", continent: .africa, capital: "Antananarivo", funFact: "Fourth-largest island in the world"),
        Country(name: "Malawi", flag: "🇲🇼", code: "MW", continent: .africa, capital: "Lilongwe", funFact: "Known as 'The Warm Heart of Africa'"),
        Country(name: "Mali", flag: "🇲🇱", code: "ML", continent: .africa, capital: "Bamako", funFact: "Home to the ancient city of Timbuktu"),
        Country(name: "Mauritania", flag: "🇲🇷", code: "MR", continent: .africa, capital: "Nouakchott", funFact: "Flag features a crescent and star"),
        Country(name: "Mauritius", flag: "🇲🇺", code: "MU", continent: .africa, capital: "Port Louis", funFact: "Home of the now-extinct dodo bird"),
        Country(name: "Morocco", flag: "🇲🇦", code: "MA", continent: .africa, capital: "Rabat", funFact: "Has a green star on a red background"),
        Country(name: "Mozambique", flag: "🇲🇿", code: "MZ", continent: .africa, capital: "Maputo", funFact: "Only flag in the world with a rifle"),
        Country(name: "Namibia", flag: "🇳🇦", code: "NA", continent: .africa, capital: "Windhoek", funFact: "Has the world's oldest desert"),
        Country(name: "Niger", flag: "🇳🇪", code: "NE", continent: .africa, capital: "Niamey", funFact: "Named after the Niger River"),
        Country(name: "Nigeria", flag: "🇳🇬", code: "NG", continent: .africa, capital: "Abuja", funFact: "Most populous country in Africa"),
        Country(name: "Rwanda", flag: "🇷🇼", code: "RW", continent: .africa, capital: "Kigali", funFact: "Known as the 'Land of a Thousand Hills'"),
        Country(name: "São Tomé and Príncipe", flag: "🇸🇹", code: "ST", continent: .africa, capital: "São Tomé", funFact: "Second-smallest African country"),
        Country(name: "Senegal", flag: "🇸🇳", code: "SN", continent: .africa, capital: "Dakar", funFact: "Has a green star on its flag"),
        Country(name: "Seychelles", flag: "🇸🇨", code: "SC", continent: .africa, capital: "Victoria", funFact: "Has a unique radiating flag design"),
        Country(name: "Sierra Leone", flag: "🇸🇱", code: "SL", continent: .africa, capital: "Freetown", funFact: "Name means 'Lion Mountains'"),
        Country(name: "Somalia", flag: "🇸🇴", code: "SO", continent: .africa, capital: "Mogadishu", funFact: "Has a white star on blue background"),
        Country(name: "South Africa", flag: "🇿🇦", code: "ZA", continent: .africa, capital: "Pretoria", funFact: "Has three capital cities"),
        Country(name: "South Sudan", flag: "🇸🇸", code: "SS", continent: .africa, capital: "Juba", funFact: "World's newest country (2011)"),
        Country(name: "Sudan", flag: "🇸🇩", code: "SD", continent: .africa, capital: "Khartoum", funFact: "Has more pyramids than Egypt"),
        Country(name: "Tanzania", flag: "🇹🇿", code: "TZ", continent: .africa, capital: "Dodoma", funFact: "Home to Mount Kilimanjaro"),
        Country(name: "Togo", flag: "🇹🇬", code: "TG", continent: .africa, capital: "Lomé", funFact: "One of the smallest countries in Africa"),
        Country(name: "Tunisia", flag: "🇹🇳", code: "TN", continent: .africa, capital: "Tunis", funFact: "Has a crescent and star on its flag"),
        Country(name: "Uganda", flag: "🇺🇬", code: "UG", continent: .africa, capital: "Kampala", funFact: "Has a crane bird on its flag"),
        Country(name: "Zambia", flag: "🇿🇲", code: "ZM", continent: .africa, capital: "Lusaka", funFact: "Home to Victoria Falls"),
        Country(name: "Zimbabwe", flag: "🇿🇼", code: "ZW", continent: .africa, capital: "Harare", funFact: "Has a bird emblem on its flag"),

        // ─── ASIA ───
        Country(name: "Afghanistan", flag: "🇦🇫", code: "AF", continent: .asia, capital: "Kabul", funFact: "Has a mosque emblem on its flag"),
        Country(name: "Armenia", flag: "🇦🇲", code: "AM", continent: .asia, capital: "Yerevan", funFact: "One of the oldest civilizations"),
        Country(name: "Azerbaijan", flag: "🇦🇿", code: "AZ", continent: .asia, capital: "Baku", funFact: "Known as the 'Land of Fire'"),
        Country(name: "Bahrain", flag: "🇧🇭", code: "BH", continent: .asia, capital: "Manama", funFact: "Smallest country in the Middle East"),
        Country(name: "Bangladesh", flag: "🇧🇩", code: "BD", continent: .asia, capital: "Dhaka", funFact: "Flag has a red circle on green"),
        Country(name: "Bhutan", flag: "🇧🇹", code: "BT", continent: .asia, capital: "Thimphu", funFact: "Has a dragon on its flag"),
        Country(name: "Brunei", flag: "🇧🇳", code: "BN", continent: .asia, capital: "Bandar Seri Begawan", funFact: "One of the richest countries"),
        Country(name: "Cambodia", flag: "🇰🇭", code: "KH", continent: .asia, capital: "Phnom Penh", funFact: "Only flag with a building on it"),
        Country(name: "China", flag: "🇨🇳", code: "CN", continent: .asia, capital: "Beijing", funFact: "Most populous country in the world"),
        Country(name: "Cyprus", flag: "🇨🇾", code: "CY", continent: .asia, capital: "Nicosia", funFact: "Shows the island shape on its flag"),
        Country(name: "Georgia", flag: "🇬🇪", code: "GE", continent: .asia, capital: "Tbilisi", funFact: "Has five crosses on its flag"),
        Country(name: "India", flag: "🇮🇳", code: "IN", continent: .asia, capital: "New Delhi", funFact: "Has a spinning wheel on its flag"),
        Country(name: "Indonesia", flag: "🇮🇩", code: "ID", continent: .asia, capital: "Jakarta", funFact: "Largest island country in the world"),
        Country(name: "Iran", flag: "🇮🇷", code: "IR", continent: .asia, capital: "Tehran", funFact: "Has 'God is Great' written on its flag"),
        Country(name: "Iraq", flag: "🇮🇶", code: "IQ", continent: .asia, capital: "Baghdad", funFact: "Has 'God is Great' in Arabic on its flag"),
        Country(name: "Israel", flag: "🇮🇱", code: "IL", continent: .asia, capital: "Jerusalem", funFact: "Has the Star of David on its flag"),
        Country(name: "Japan", flag: "🇯🇵", code: "JP", continent: .asia, capital: "Tokyo", funFact: "Flag is called the 'Circle of the Sun'"),
        Country(name: "Jordan", flag: "🇯🇴", code: "JO", continent: .asia, capital: "Amman", funFact: "Has a seven-pointed star on its flag"),
        Country(name: "Kazakhstan", flag: "🇰🇿", code: "KZ", continent: .asia, capital: "Astana", funFact: "Largest landlocked country in the world"),
        Country(name: "Kuwait", flag: "🇰🇼", code: "KW", continent: .asia, capital: "Kuwait City", funFact: "One of the richest countries per capita"),
        Country(name: "Kyrgyzstan", flag: "🇰🇬", code: "KG", continent: .asia, capital: "Bishkek", funFact: "Has a sun with 40 rays on its flag"),
        Country(name: "Laos", flag: "🇱🇦", code: "LA", continent: .asia, capital: "Vientiane", funFact: "Has a white circle on its flag"),
        Country(name: "Lebanon", flag: "🇱🇧", code: "LB", continent: .asia, capital: "Beirut", funFact: "Has a cedar tree on its flag"),
        Country(name: "Malaysia", flag: "🇲🇾", code: "MY", continent: .asia, capital: "Kuala Lumpur", funFact: "Flag has 14 stripes"),
        Country(name: "Maldives", flag: "🇲🇻", code: "MV", continent: .asia, capital: "Malé", funFact: "Lowest country in the world"),
        Country(name: "Mongolia", flag: "🇲🇳", code: "MN", continent: .asia, capital: "Ulaanbaatar", funFact: "Has a Soyombo symbol on its flag"),
        Country(name: "Myanmar", flag: "🇲🇲", code: "MM", continent: .asia, capital: "Naypyidaw", funFact: "Has a large white star on its flag"),
        Country(name: "Nepal", flag: "🇳🇵", code: "NP", continent: .asia, capital: "Kathmandu", funFact: "Only non-rectangular national flag"),
        Country(name: "North Korea", flag: "🇰🇵", code: "KP", continent: .asia, capital: "Pyongyang", funFact: "Has a red star on its flag"),
        Country(name: "Oman", flag: "🇴🇲", code: "OM", continent: .asia, capital: "Muscat", funFact: "Has a dagger and swords on its flag"),
        Country(name: "Pakistan", flag: "🇵🇰", code: "PK", continent: .asia, capital: "Islamabad", funFact: "Has a crescent and star on green"),
        Country(name: "Palestine", flag: "🇵🇸", code: "PS", continent: .asia, capital: "Ramallah", funFact: "Uses Pan-Arab colors"),
        Country(name: "Philippines", flag: "🇵🇭", code: "PH", continent: .asia, capital: "Manila", funFact: "Flag is flipped upside down in wartime"),
        Country(name: "Qatar", flag: "🇶🇦", code: "QA", continent: .asia, capital: "Doha", funFact: "Has a unique maroon and white flag"),
        Country(name: "Saudi Arabia", flag: "🇸🇦", code: "SA", continent: .asia, capital: "Riyadh", funFact: "Has a sword and Arabic text on its flag"),
        Country(name: "Singapore", flag: "🇸🇬", code: "SG", continent: .asia, capital: "Singapore", funFact: "One of only three city-states"),
        Country(name: "South Korea", flag: "🇰🇷", code: "KR", continent: .asia, capital: "Seoul", funFact: "Flag has yin-yang and trigrams"),
        Country(name: "Sri Lanka", flag: "🇱🇰", code: "LK", continent: .asia, capital: "Sri Jayawardenepura Kotte", funFact: "Has a lion holding a sword on its flag"),
        Country(name: "Syria", flag: "🇸🇾", code: "SY", continent: .asia, capital: "Damascus", funFact: "Has two green stars on its flag"),
        Country(name: "Taiwan", flag: "🇹🇼", code: "TW", continent: .asia, capital: "Taipei", funFact: "Has a white sun on blue and red"),
        Country(name: "Tajikistan", flag: "🇹🇯", code: "TJ", continent: .asia, capital: "Dushanbe", funFact: "Has a crown and stars on its flag"),
        Country(name: "Thailand", flag: "🇹🇭", code: "TH", continent: .asia, capital: "Bangkok", funFact: "Flag has red, white, and blue stripes"),
        Country(name: "Timor-Leste", flag: "🇹🇱", code: "TL", continent: .asia, capital: "Dili", funFact: "One of the newest countries in Asia"),
        Country(name: "Turkey", flag: "🇹🇷", code: "TR", continent: .asia, capital: "Ankara", funFact: "Has a crescent and star on red"),
        Country(name: "Turkmenistan", flag: "🇹🇲", code: "TM", continent: .asia, capital: "Ashgabat", funFact: "Has the most complex flag design"),
        Country(name: "United Arab Emirates", flag: "🇦🇪", code: "AE", continent: .asia, capital: "Abu Dhabi", funFact: "Made up of seven emirates"),
        Country(name: "Uzbekistan", flag: "🇺🇿", code: "UZ", continent: .asia, capital: "Tashkent", funFact: "Has a crescent moon and 12 stars"),
        Country(name: "Vietnam", flag: "🇻🇳", code: "VN", continent: .asia, capital: "Hanoi", funFact: "Has a yellow star on red background"),
        Country(name: "Yemen", flag: "🇾🇪", code: "YE", continent: .asia, capital: "Sana'a", funFact: "Has simple red, white, and black stripes"),

        // ─── EUROPE ───
        Country(name: "Albania", flag: "🇦🇱", code: "AL", continent: .europe, capital: "Tirana", funFact: "Has a double-headed eagle on its flag"),
        Country(name: "Andorra", flag: "🇦🇩", code: "AD", continent: .europe, capital: "Andorra la Vella", funFact: "Tiny country between France and Spain"),
        Country(name: "Austria", flag: "🇦🇹", code: "AT", continent: .europe, capital: "Vienna", funFact: "One of the oldest flags in the world"),
        Country(name: "Belarus", flag: "🇧🇾", code: "BY", continent: .europe, capital: "Minsk", funFact: "Has a decorative pattern on its flag"),
        Country(name: "Belgium", flag: "🇧🇪", code: "BE", continent: .europe, capital: "Brussels", funFact: "Has vertical black, yellow, red stripes"),
        Country(name: "Bosnia and Herzegovina", flag: "🇧🇦", code: "BA", continent: .europe, capital: "Sarajevo", funFact: "Flag has stars and a triangle"),
        Country(name: "Bulgaria", flag: "🇧🇬", code: "BG", continent: .europe, capital: "Sofia", funFact: "Has white, green, and red stripes"),
        Country(name: "Croatia", flag: "🇭🇷", code: "HR", continent: .europe, capital: "Zagreb", funFact: "Has a checkered coat of arms on its flag"),
        Country(name: "Czech Republic", flag: "🇨🇿", code: "CZ", continent: .europe, capital: "Prague", funFact: "Has a blue triangle on its flag"),
        Country(name: "Denmark", flag: "🇩🇰", code: "DK", continent: .europe, capital: "Copenhagen", funFact: "Has the oldest flag still in use"),
        Country(name: "Estonia", flag: "🇪🇪", code: "EE", continent: .europe, capital: "Tallinn", funFact: "Blue represents the sky and lakes"),
        Country(name: "Finland", flag: "🇫🇮", code: "FI", continent: .europe, capital: "Helsinki", funFact: "Has a blue Nordic cross on white"),
        Country(name: "France", flag: "🇫🇷", code: "FR", continent: .europe, capital: "Paris", funFact: "Blue, white, and red vertical stripes"),
        Country(name: "Germany", flag: "🇩🇪", code: "DE", continent: .europe, capital: "Berlin", funFact: "Black, red, and gold horizontal stripes"),
        Country(name: "Greece", flag: "🇬🇷", code: "GR", continent: .europe, capital: "Athens", funFact: "Blue and white stripes with a cross"),
        Country(name: "Hungary", flag: "🇭🇺", code: "HU", continent: .europe, capital: "Budapest", funFact: "Red, white, and green horizontal stripes"),
        Country(name: "Iceland", flag: "🇮🇸", code: "IS", continent: .europe, capital: "Reykjavík", funFact: "Has a red Nordic cross on blue"),
        Country(name: "Ireland", flag: "🇮🇪", code: "IE", continent: .europe, capital: "Dublin", funFact: "Green, white, and orange vertical stripes"),
        Country(name: "Italy", flag: "🇮🇹", code: "IT", continent: .europe, capital: "Rome", funFact: "Green, white, and red vertical stripes"),
        Country(name: "Kosovo", flag: "🇽🇰", code: "XK", continent: .europe, capital: "Pristina", funFact: "Shows the country's shape on its flag"),
        Country(name: "Latvia", flag: "🇱🇻", code: "LV", continent: .europe, capital: "Riga", funFact: "Has a unique dark red (maroon) color"),
        Country(name: "Liechtenstein", flag: "🇱🇮", code: "LI", continent: .europe, capital: "Vaduz", funFact: "Has a crown on its flag"),
        Country(name: "Lithuania", flag: "🇱🇹", code: "LT", continent: .europe, capital: "Vilnius", funFact: "Yellow, green, and red horizontal stripes"),
        Country(name: "Luxembourg", flag: "🇱🇺", code: "LU", continent: .europe, capital: "Luxembourg City", funFact: "Looks similar to the Dutch flag"),
        Country(name: "Malta", flag: "🇲🇹", code: "MT", continent: .europe, capital: "Valletta", funFact: "Has a George Cross on its flag"),
        Country(name: "Moldova", flag: "🇲🇩", code: "MD", continent: .europe, capital: "Chișinău", funFact: "Has a coat of arms with an eagle"),
        Country(name: "Monaco", flag: "🇲🇨", code: "MC", continent: .europe, capital: "Monaco", funFact: "Flag looks like Indonesia's flag"),
        Country(name: "Montenegro", flag: "🇲🇪", code: "ME", continent: .europe, capital: "Podgorica", funFact: "Has a double-headed eagle on red"),
        Country(name: "Netherlands", flag: "🇳🇱", code: "NL", continent: .europe, capital: "Amsterdam", funFact: "Red, white, and blue horizontal stripes"),
        Country(name: "North Macedonia", flag: "🇲🇰", code: "MK", continent: .europe, capital: "Skopje", funFact: "Has a sun with rays on its flag"),
        Country(name: "Norway", flag: "🇳🇴", code: "NO", continent: .europe, capital: "Oslo", funFact: "Has a blue Nordic cross on red"),
        Country(name: "Poland", flag: "🇵🇱", code: "PL", continent: .europe, capital: "Warsaw", funFact: "Simple white and red horizontal stripes"),
        Country(name: "Portugal", flag: "🇵🇹", code: "PT", continent: .europe, capital: "Lisbon", funFact: "Has a coat of arms on green and red"),
        Country(name: "Romania", flag: "🇷🇴", code: "RO", continent: .europe, capital: "Bucharest", funFact: "Blue, yellow, and red vertical stripes"),
        Country(name: "Russia", flag: "🇷🇺", code: "RU", continent: .europe, capital: "Moscow", funFact: "White, blue, and red horizontal stripes"),
        Country(name: "San Marino", flag: "🇸🇲", code: "SM", continent: .europe, capital: "San Marino", funFact: "One of the oldest republics in the world"),
        Country(name: "Serbia", flag: "🇷🇸", code: "RS", continent: .europe, capital: "Belgrade", funFact: "Has a coat of arms with a double eagle"),
        Country(name: "Slovakia", flag: "🇸🇰", code: "SK", continent: .europe, capital: "Bratislava", funFact: "Has a double cross on three hills"),
        Country(name: "Slovenia", flag: "🇸🇮", code: "SI", continent: .europe, capital: "Ljubljana", funFact: "Has Mount Triglav on its coat of arms"),
        Country(name: "Spain", flag: "🇪🇸", code: "ES", continent: .europe, capital: "Madrid", funFact: "Has a coat of arms on red and yellow"),
        Country(name: "Sweden", flag: "🇸🇪", code: "SE", continent: .europe, capital: "Stockholm", funFact: "Has a yellow Nordic cross on blue"),
        Country(name: "Switzerland", flag: "🇨🇭", code: "CH", continent: .europe, capital: "Bern", funFact: "One of only two square flags"),
        Country(name: "Ukraine", flag: "🇺🇦", code: "UA", continent: .europe, capital: "Kyiv", funFact: "Blue and yellow represent sky and wheat"),
        Country(name: "United Kingdom", flag: "🇬🇧", code: "GB", continent: .europe, capital: "London", funFact: "Flag combines three crosses"),
        Country(name: "Vatican City", flag: "🇻🇦", code: "VA", continent: .europe, capital: "Vatican City", funFact: "Smallest country in the world"),

        // ─── NORTH AMERICA ───
        Country(name: "Antigua and Barbuda", flag: "🇦🇬", code: "AG", continent: .northAmerica, capital: "St. John's", funFact: "Has a rising sun on its flag"),
        Country(name: "Bahamas", flag: "🇧🇸", code: "BS", continent: .northAmerica, capital: "Nassau", funFact: "Has aquamarine stripes and black triangle"),
        Country(name: "Barbados", flag: "🇧🇧", code: "BB", continent: .northAmerica, capital: "Bridgetown", funFact: "Has a trident on its flag"),
        Country(name: "Belize", flag: "🇧🇿", code: "BZ", continent: .northAmerica, capital: "Belmopan", funFact: "Has a coat of arms with two men"),
        Country(name: "Canada", flag: "🇨🇦", code: "CA", continent: .northAmerica, capital: "Ottawa", funFact: "Has a maple leaf on its flag"),
        Country(name: "Costa Rica", flag: "🇨🇷", code: "CR", continent: .northAmerica, capital: "San José", funFact: "Blue, white, and red horizontal stripes"),
        Country(name: "Cuba", flag: "🇨🇺", code: "CU", continent: .northAmerica, capital: "Havana", funFact: "Has a white star on a red triangle"),
        Country(name: "Dominica", flag: "🇩🇲", code: "DM", continent: .northAmerica, capital: "Roseau", funFact: "Has a parrot on its flag"),
        Country(name: "Dominican Republic", flag: "🇩🇴", code: "DO", continent: .northAmerica, capital: "Santo Domingo", funFact: "Only flag with a Bible on it"),
        Country(name: "El Salvador", flag: "🇸🇻", code: "SV", continent: .northAmerica, capital: "San Salvador", funFact: "Has a coat of arms with volcanoes"),
        Country(name: "Grenada", flag: "🇬🇩", code: "GD", continent: .northAmerica, capital: "St. George's", funFact: "Has a nutmeg on its flag"),
        Country(name: "Guatemala", flag: "🇬🇹", code: "GT", continent: .northAmerica, capital: "Guatemala City", funFact: "Has a quetzal bird on its coat of arms"),
        Country(name: "Haiti", flag: "🇭🇹", code: "HT", continent: .northAmerica, capital: "Port-au-Prince", funFact: "Has a coat of arms with a palm tree"),
        Country(name: "Honduras", flag: "🇭🇳", code: "HN", continent: .northAmerica, capital: "Tegucigalpa", funFact: "Has five blue stars on its flag"),
        Country(name: "Jamaica", flag: "🇯🇲", code: "JM", continent: .northAmerica, capital: "Kingston", funFact: "Only flag with no red, white, or blue"),
        Country(name: "Mexico", flag: "🇲🇽", code: "MX", continent: .northAmerica, capital: "Mexico City", funFact: "Has an eagle eating a snake"),
        Country(name: "Nicaragua", flag: "🇳🇮", code: "NI", continent: .northAmerica, capital: "Managua", funFact: "Has a triangle with a rainbow on it"),
        Country(name: "Panama", flag: "🇵🇦", code: "PA", continent: .northAmerica, capital: "Panama City", funFact: "Has stars on a white background"),
        Country(name: "Saint Kitts and Nevis", flag: "🇰🇳", code: "KN", continent: .northAmerica, capital: "Basseterre", funFact: "Has two white stars on a black stripe"),
        Country(name: "Saint Lucia", flag: "🇱🇨", code: "LC", continent: .northAmerica, capital: "Castries", funFact: "Has a triangle on a blue background"),
        Country(name: "Saint Vincent and the Grenadines", flag: "🇻🇨", code: "VC", continent: .northAmerica, capital: "Kingstown", funFact: "Has green diamonds on its flag"),
        Country(name: "Trinidad and Tobago", flag: "🇹🇹", code: "TT", continent: .northAmerica, capital: "Port of Spain", funFact: "Has a diagonal black stripe"),
        Country(name: "United States", flag: "🇺🇸", code: "US", continent: .northAmerica, capital: "Washington, D.C.", funFact: "Has 50 stars for 50 states"),

        // ─── SOUTH AMERICA ───
        Country(name: "Argentina", flag: "🇦🇷", code: "AR", continent: .southAmerica, capital: "Buenos Aires", funFact: "Has a sun with a face on its flag"),
        Country(name: "Bolivia", flag: "🇧🇴", code: "BO", continent: .southAmerica, capital: "Sucre", funFact: "Has red, yellow, and green stripes"),
        Country(name: "Brazil", flag: "🇧🇷", code: "BR", continent: .southAmerica, capital: "Brasília", funFact: "Has stars representing its states"),
        Country(name: "Chile", flag: "🇨🇱", code: "CL", continent: .southAmerica, capital: "Santiago", funFact: "Looks similar to the Texas flag"),
        Country(name: "Colombia", flag: "🇨🇴", code: "CO", continent: .southAmerica, capital: "Bogotá", funFact: "Yellow stripe is twice as wide"),
        Country(name: "Ecuador", flag: "🇪🇨", code: "EC", continent: .southAmerica, capital: "Quito", funFact: "Has a coat of arms with a condor"),
        Country(name: "Guyana", flag: "🇬🇾", code: "GY", continent: .southAmerica, capital: "Georgetown", funFact: "Called the 'Golden Arrowhead' flag"),
        Country(name: "Paraguay", flag: "🇵🇾", code: "PY", continent: .southAmerica, capital: "Asunción", funFact: "Different emblems on each side"),
        Country(name: "Peru", flag: "🇵🇪", code: "PE", continent: .southAmerica, capital: "Lima", funFact: "Has red and white vertical stripes"),
        Country(name: "Suriname", flag: "🇸🇷", code: "SR", continent: .southAmerica, capital: "Paramaribo", funFact: "Has a star on green, white, red stripes"),
        Country(name: "Uruguay", flag: "🇺🇾", code: "UY", continent: .southAmerica, capital: "Montevideo", funFact: "Has a sun with a face like Argentina"),
        Country(name: "Venezuela", flag: "🇻🇪", code: "VE", continent: .southAmerica, capital: "Caracas", funFact: "Has eight stars on its flag"),

        // ─── OCEANIA ───
        Country(name: "Australia", flag: "🇦🇺", code: "AU", continent: .oceania, capital: "Canberra", funFact: "Has the Southern Cross on its flag"),
        Country(name: "Fiji", flag: "🇫🇯", code: "FJ", continent: .oceania, capital: "Suva", funFact: "Has a coat of arms with a lion"),
        Country(name: "Kiribati", flag: "🇰🇮", code: "KI", continent: .oceania, capital: "South Tarawa", funFact: "Has a bird over ocean waves"),
        Country(name: "Marshall Islands", flag: "🇲🇭", code: "MH", continent: .oceania, capital: "Majuro", funFact: "Has a star with 24 points"),
        Country(name: "Micronesia", flag: "🇫🇲", code: "FM", continent: .oceania, capital: "Palikir", funFact: "Has four stars on a blue background"),
        Country(name: "Nauru", flag: "🇳🇷", code: "NR", continent: .oceania, capital: "Yaren", funFact: "Smallest island country in the world"),
        Country(name: "New Zealand", flag: "🇳🇿", code: "NZ", continent: .oceania, capital: "Wellington", funFact: "Has four red stars on its flag"),
        Country(name: "Palau", flag: "🇵🇼", code: "PW", continent: .oceania, capital: "Ngerulmud", funFact: "Has a yellow circle on blue"),
        Country(name: "Papua New Guinea", flag: "🇵🇬", code: "PG", continent: .oceania, capital: "Port Moresby", funFact: "Has a bird of paradise on its flag"),
        Country(name: "Samoa", flag: "🇼🇸", code: "WS", continent: .oceania, capital: "Apia", funFact: "Has the Southern Cross constellation"),
        Country(name: "Solomon Islands", flag: "🇸🇧", code: "SB", continent: .oceania, capital: "Honiara", funFact: "Has five white stars on its flag"),
        Country(name: "Tonga", flag: "🇹🇴", code: "TO", continent: .oceania, capital: "Nukuʻalofa", funFact: "Has a red cross on a white square"),
        Country(name: "Tuvalu", flag: "🇹🇻", code: "TV", continent: .oceania, capital: "Funafuti", funFact: "Fourth-smallest country in the world"),
        Country(name: "Vanuatu", flag: "🇻🇺", code: "VU", continent: .oceania, capital: "Port Vila", funFact: "Has a boar tusk on its flag"),
    ]

    static func countries(for continent: Continent) -> [Country] {
        if continent == .all {
            return allCountries
        }
        return allCountries.filter { $0.continent == continent }
    }
}
